apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodu
  labels:
    app: hodu
  namespace: wacruit-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hodu
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: hodu
    spec:
      containers:
      - image: #TODO
        name: hodu
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: wacruit-dev
  name: hodu
spec:
  type: ClusterIP
  selector:
    app: hodu
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: wacruit-dev
  name: hodu
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - #TODO
    http:
  - route:
    - destination:
        host: hodu