apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodu-server
  labels:
    app: hodu-server
  namespace: hodu-prod
spec:
  replicas: 0
   selector:
    matchLabels:
      app: hodu-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: hodu-server
    spec:
      serviceAccountName: hodu-server
      containers:
      - image: #TODO
        name: hodu-server
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hodu-server
  namespace: hodu-prod
  annotations:
    eks.amazonaws.com/role-arn: #TODO
---
apiVersion: v1
kind: Service
metadata:
  namespace: hodu-prod
  name: hodu-server
spec:
  type: ClusterIP
  selector:
    app: hodu-server
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: hodu-prod
  name: hodu-server
spec:
  gateways:
  - istio-ingress/waffle-ingressgateway
  - mesh
  hosts:
  - hodu-server.hodu-prod.svc.cluster.local
  http:
  - route:
    - destination:
        host: hodu-server